name: service-application-tech-stack
services:
  postgres:
    image: postgres:18.4
    container_name: sats-postgres
    environment:
      - POSTGRES_PASSWORD=${SATS_POSTGRES_PASSWORD:-pass}
      - POSTGRES_DB=sats
    ports:
      - 5432:5432
  openbao:
    image: openbao/openbao:2.6.1
    container_name: sats-openbao
    ports:
      - 8200:8200
    environment:
      - BAO_DEV_ROOT_TOKEN_ID=${SATS_OPENBAO_DEV_TOKEN}
  # https://www.keycloak.org/getting-started/getting-started-docker
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.4
    container_name: sats-keycloak
    ports:
      - 8070:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${SATS_KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${SATS_KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
