# OIDC client credential configurations set via Vault secret config.

quarkus:
  vault:
    # https://docs.quarkiverse.io/quarkus-vault/dev/index.html#quarkus-vault_quarkus-vault-secret-config-kv-path-prefix
    secret-config-kv-path:
      sats-oidc-client-secret:
        # the secret path in OpenBao
        - oidc-client

  # https://quarkus.io/guides/security-oidc-configuration-properties-reference/
  oidc:
    credentials:
      # Use prefixed MP config properties, i.e. ${PREFIX.SECRET-KEY}.
      # option 1:
      secret: ${sats-oidc-client-secret.client-secret}
      # option 2:
      #client-secret:
      # value: ${sats-oidc-client-secret.client-secret}
