quarkus:
  profile:
    - dev
    # - datasource-credential-password
    - datasource-credential-vault
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/sats
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  vault:
    url: ${SATS_OPENBAO_ADDR}
    authentication:
      # app-role:
      #   role-id:
      #   secret-id:
      userpass:
        auth-mount-path: sats-userpass
        username: sats-user
        password: sats-pass
      # client-token: ${SATS_OPENBAO_DEV_TOKEN}
