quarkus:
  vault:
    kv-secret-engine-mount-path: sats/kv
    credentials-provider:
      # Define a credentials provider for below to use.
      sats-postgres:
        kv-path: db
        # Must specify these in case of using unusual secret keys.
        # kv-username-key: username
        # kv-password-key: password
  datasource:
    # Specify the defined provider, so Quarkus will use the provider's configuration to
    # communicate with Vault server and get the authentication used for database connections.
    credentials-provider: sats-postgres
