quarkus:
  profile:
    - dev
    # - datasource-credential-password
    - datasource-credential-vault
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/sats
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  # https://docs.quarkiverse.io/quarkus-vault/dev/index.html
  vault:
    url: ${SATS_OPENBAO_ADDR}
    authentication:
      app-role:
        auth-mount-path: sats-approle
        role-id: 01234567-89ab-cdef-0123-4567890abcde
        secret-id: edcba098-7654-3210-fedc-ba9876543210
      # userpass:
      #   auth-mount-path: sats-userpass
      #   username: sats-user
      #   password: sats-pass
      # client-token: ${SATS_OPENBAO_DEV_TOKEN}
