# OIDC client credential configurations set via a built-in Vault credential provider.
# NOTE:
# this is more like a workaround/approach, relying on a incomprehensible path:
# using a Quarkus built-in CredentialsProvider bean named "vault-credentials-provider" (?),
# setting its password-key to that storing OIDC client key,
# using the "password" credential key as OIDC client secret.
# Maybe it's little better to have a custom CredentialsProvider implementation ..?

quarkus:
  # https://docs.quarkiverse.io/quarkus-vault/dev/index.html
  vault:
    credentials-provider:
      # Define a credentials provider for below to use.
      sats-oidc-client-secret:
        # for KV v2 engine
        kv-path: oidc-client
        # Use the password key as client secret key; the username key is unused
        # kv-username-key: UNUSED
        kv-password-key: client-secret

  # https://quarkus.io/guides/security-oidc-configuration-properties-reference/
  oidc:
    credentials:
      client-secret:
        # provide client secret via credential provider
        provider:
          # the bean name of credential provider to use; see io.quarkus.vault.runtime.VaultCredentialsProvider
          name: vault-credentials-provider
          # TODO: not sure but seems it is the credentials provider named at quarkus.vault.credentials-provider
          keyring-name: sats-oidc-client-secret
          # the CredentialsProvider credential key of the map that presents the secret
          key: password
