quarkus:
  # https://docs.quarkiverse.io/quarkus-vault/dev/index.html
  vault:
    credentials-provider:
      # Define a credentials provider for below to use.
      sats-postgres:
        # for KV v2 engine
        # kv-path: db
        # Must specify these in case of using unusual secret keys.
        # kv-username-key: username
        # kv-password-key: password

        # for database engine
        credentials-role: sats-database-role
        credentials-mount: sats/database
        # credentials-request-path: creds
  datasource:
    # Specify the defined provider, so Quarkus will use the provider's configuration to
    # communicate with Vault server and get the authentication used for database connections.
    credentials-provider: sats-postgres
