# OIDC client credential configurations set via environment variables

quarkus:
  # https://quarkus.io/guides/security-oidc-configuration-properties-reference/
  oidc:
    credentials:
      # option 1:
      secret: ${SATS_OIDC_CLIENT_SECRET}
      # option 2:
      #client-secret:
      #  value: ${SATS_OIDC_CLIENT_SECRET}
